[package]
name = "uniffi-bindgen-java"
version = "0.1.0"
edition = "2021"

[lib]
name = "uniffi_bindgen_java"
path = "src/lib.rs"

[[bin]]
name = "uniffi-bindgen-java"
path = "src/main.rs"

[dependencies]
anyhow = "1"
askama = { version = "0.12", default-features = false, features = ["config"] }
camino = "1.1.6"
cargo_metadata = "0.15"
clap = { version = "4", default-features = false, features = [
    "derive",
    "help",
    "std",
    "cargo",
] }
heck = "0.5"
once_cell = "1.19.0"
paste = "1"
regex = "1.10.4"
serde = "1"
textwrap = "0.16.1"
toml = "0.5" # can't be on 8, `Value` is part of public interface
# uniffi_bindgen = { path = "../uniffi-rs/uniffi_bindgen" }
# uniffi_meta = { path = "../uniffi-rs/uniffi_meta" }
uniffi_bindgen = { git = "https://github.com/giarc3/uniffi-rs.git", branch = "oneshot-test" }
uniffi_meta = { git = "https://github.com/giarc3/uniffi-rs.git", branch = "oneshot-test" }
[dev-dependencies]
glob = "0.3"
itertools = "0.13.0"
# uniffi-example-arithmetic = { path = "../uniffi-rs/examples/arithmetic" }
# uniffi-example-custom-types = { path = "../uniffi-rs/examples/custom-types" }
# uniffi-example-futures = { path = "../uniffi-rs/examples/futures" }
# uniffi-example-geometry = { path = "../uniffi-rs/examples/geometry" }
# uniffi-example-rondpoint = { path = "../uniffi-rs/examples/rondpoint" }
# uniffi-fixture-coverall = { path = "../uniffi-rs/fixtures/coverall" }
# uniffi-fixture-ext-types = { path = "../uniffi-rs/fixtures/ext-types/lib" }
# uniffi-fixture-futures = { path = "../uniffi-rs/fixtures/futures" }
# uniffi-fixture-time = { path = "../uniffi-rs/fixtures/uniffi-fixture-time" }
# uniffi_testing = { path = "../uniffi-rs/uniffi_testing" }
uniffi-example-arithmetic = { git = "https://github.com/giarc3/uniffi-rs.git", branch = "oneshot-test" }
uniffi-example-custom-types = { git = "https://github.com/giarc3/uniffi-rs.git", branch = "oneshot-test" }
uniffi-example-futures = { git = "https://github.com/giarc3/uniffi-rs.git", branch = "oneshot-test" }
uniffi-example-geometry = { git = "https://github.com/giarc3/uniffi-rs.git", branch = "oneshot-test" }
uniffi-example-rondpoint = { git = "https://github.com/giarc3/uniffi-rs.git", branch = "oneshot-test" }
uniffi-fixture-coverall = { git = "https://github.com/giarc3/uniffi-rs.git", branch = "oneshot-test" }
uniffi-fixture-ext-types = { git = "https://github.com/giarc3/uniffi-rs.git", branch = "oneshot-test" }
uniffi-fixture-futures = { git = "https://github.com/giarc3/uniffi-rs.git", branch = "oneshot-test" }
uniffi-fixture-time = { git = "https://github.com/giarc3/uniffi-rs.git", branch = "oneshot-test" }
uniffi_testing = { git = "https://github.com/giarc3/uniffi-rs.git", branch = "oneshot-test" }
